# Generated by Django 6.0.5 on 2026-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedactivity',
            name='scope',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
